# https://docs.hedgedoc.org/setup/docker/
# https://docs.hedgedoc.org/configuration/
services:
  database:
    # image: postgres:13.4-alpine
    # everything before 14 uses md5...
    # https://hub.docker.com/_/postgres
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=$USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    networks:
      - hedge
  doc-app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    # < version 2 though...
    image: quay.io/hedgedoc/hedgedoc:1.9.7
    environment:
      - CMD_DB_URL=postgres://$USER:$PG_PASSWORD@database:5432/hedgedoc
      # - CMD_DOMAIN=localhost
      # - CMD_URL_ADDPORT=true
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_ALLOW_FREEURL=true
      - CMD_EMAIL=true
      - CMD_ALLOW_EMAIL_REGISTER=true
      - CMD_ALLOW_GRAVATAR=false
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      # only use wireguard ip
      - "$WG_IP:3000:3000"
    restart: always
    depends_on:
      - database
    networks:
      - hedge
  # not related to hedgedoc, but just the infra we all need
  # rev-sync uses redis
  # not really sure on redis being used by more things  
  rev-redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
    # this might not work since redis puts its own volume
    volumes:
      - redis:/data
    ports:
      - "$WG_IP:6379:6379"
    networks:
      - rev
  web-server:
    image: caddy:alpine
    ports: 
      - "$WG_IP:80:80"
      - "$WG_IP:443:443"
    environment:
      - CADDY_SITE=$WG_IP
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile  
    networks:
      - server

volumes:
  database:
  uploads:
  redis:

networks:
  hedge:
  rev:
    attachable: true
  server:

configs:
  caddyfile:
    file: ./Caddyfile
  